//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("LoanAppDataBaseModel", "FK_CustomerInfo_LoanDetails", "LoanDetails", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DataBaseApp.LoanDetails), "CustomerInfo", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DataBaseApp.CustomerInfo), true)]
[assembly: EdmRelationshipAttribute("LoanAppDataBaseModel", "FK_LoanDetails_DocumentDetails", "DocumentDetails", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DataBaseApp.DocumentDetails), "LoanDetails", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DataBaseApp.LoanDetails), true)]

#endregion

namespace DataBaseApp
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class LoanAppDataBaseEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new LoanAppDataBaseEntities object using the connection string found in the 'LoanAppDataBaseEntities' section of the application configuration file.
        /// </summary>
        public LoanAppDataBaseEntities() : base("name=LoanAppDataBaseEntities", "LoanAppDataBaseEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new LoanAppDataBaseEntities object.
        /// </summary>
        public LoanAppDataBaseEntities(string connectionString) : base(connectionString, "LoanAppDataBaseEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new LoanAppDataBaseEntities object.
        /// </summary>
        public LoanAppDataBaseEntities(EntityConnection connection) : base(connection, "LoanAppDataBaseEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CustomerInfo> CustomerInfo
        {
            get
            {
                if ((_CustomerInfo == null))
                {
                    _CustomerInfo = base.CreateObjectSet<CustomerInfo>("CustomerInfo");
                }
                return _CustomerInfo;
            }
        }
        private ObjectSet<CustomerInfo> _CustomerInfo;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<DocumentDetails> DocumentDetails
        {
            get
            {
                if ((_DocumentDetails == null))
                {
                    _DocumentDetails = base.CreateObjectSet<DocumentDetails>("DocumentDetails");
                }
                return _DocumentDetails;
            }
        }
        private ObjectSet<DocumentDetails> _DocumentDetails;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<LoanDetails> LoanDetails
        {
            get
            {
                if ((_LoanDetails == null))
                {
                    _LoanDetails = base.CreateObjectSet<LoanDetails>("LoanDetails");
                }
                return _LoanDetails;
            }
        }
        private ObjectSet<LoanDetails> _LoanDetails;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CustomerInfo EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCustomerInfo(CustomerInfo customerInfo)
        {
            base.AddObject("CustomerInfo", customerInfo);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the DocumentDetails EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDocumentDetails(DocumentDetails documentDetails)
        {
            base.AddObject("DocumentDetails", documentDetails);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the LoanDetails EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLoanDetails(LoanDetails loanDetails)
        {
            base.AddObject("LoanDetails", loanDetails);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LoanAppDataBaseModel", Name="CustomerInfo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CustomerInfo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CustomerInfo object.
        /// </summary>
        /// <param name="custCode">Initial value of the CustCode property.</param>
        /// <param name="applicationNo">Initial value of the ApplicationNo property.</param>
        /// <param name="custName">Initial value of the CustName property.</param>
        /// <param name="dateOfBirth">Initial value of the DateOfBirth property.</param>
        /// <param name="age">Initial value of the Age property.</param>
        /// <param name="custEmail">Initial value of the CustEmail property.</param>
        /// <param name="custPhone">Initial value of the CustPhone property.</param>
        /// <param name="loanCode">Initial value of the LoanCode property.</param>
        public static CustomerInfo CreateCustomerInfo(global::System.Int32 custCode, global::System.Int32 applicationNo, global::System.String custName, global::System.DateTime dateOfBirth, global::System.Int16 age, global::System.String custEmail, global::System.String custPhone, global::System.String loanCode)
        {
            CustomerInfo customerInfo = new CustomerInfo();
            customerInfo.CustCode = custCode;
            customerInfo.ApplicationNo = applicationNo;
            customerInfo.CustName = custName;
            customerInfo.DateOfBirth = dateOfBirth;
            customerInfo.Age = age;
            customerInfo.CustEmail = custEmail;
            customerInfo.CustPhone = custPhone;
            customerInfo.LoanCode = loanCode;
            return customerInfo;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CustCode
        {
            get
            {
                return _CustCode;
            }
            set
            {
                if (_CustCode != value)
                {
                    OnCustCodeChanging(value);
                    ReportPropertyChanging("CustCode");
                    _CustCode = StructuralObject.SetValidValue(value, "CustCode");
                    ReportPropertyChanged("CustCode");
                    OnCustCodeChanged();
                }
            }
        }
        private global::System.Int32 _CustCode;
        partial void OnCustCodeChanging(global::System.Int32 value);
        partial void OnCustCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ApplicationNo
        {
            get
            {
                return _ApplicationNo;
            }
            set
            {
                OnApplicationNoChanging(value);
                ReportPropertyChanging("ApplicationNo");
                _ApplicationNo = StructuralObject.SetValidValue(value, "ApplicationNo");
                ReportPropertyChanged("ApplicationNo");
                OnApplicationNoChanged();
            }
        }
        private global::System.Int32 _ApplicationNo;
        partial void OnApplicationNoChanging(global::System.Int32 value);
        partial void OnApplicationNoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CustName
        {
            get
            {
                return _CustName;
            }
            set
            {
                OnCustNameChanging(value);
                ReportPropertyChanging("CustName");
                _CustName = StructuralObject.SetValidValue(value, false, "CustName");
                ReportPropertyChanged("CustName");
                OnCustNameChanged();
            }
        }
        private global::System.String _CustName;
        partial void OnCustNameChanging(global::System.String value);
        partial void OnCustNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ApplicationDate
        {
            get
            {
                return _ApplicationDate;
            }
            set
            {
                OnApplicationDateChanging(value);
                ReportPropertyChanging("ApplicationDate");
                _ApplicationDate = StructuralObject.SetValidValue(value, "ApplicationDate");
                ReportPropertyChanged("ApplicationDate");
                OnApplicationDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _ApplicationDate;
        partial void OnApplicationDateChanging(Nullable<global::System.DateTime> value);
        partial void OnApplicationDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateOfBirth
        {
            get
            {
                return _DateOfBirth;
            }
            set
            {
                OnDateOfBirthChanging(value);
                ReportPropertyChanging("DateOfBirth");
                _DateOfBirth = StructuralObject.SetValidValue(value, "DateOfBirth");
                ReportPropertyChanged("DateOfBirth");
                OnDateOfBirthChanged();
            }
        }
        private global::System.DateTime _DateOfBirth;
        partial void OnDateOfBirthChanging(global::System.DateTime value);
        partial void OnDateOfBirthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 Age
        {
            get
            {
                return _Age;
            }
            set
            {
                OnAgeChanging(value);
                ReportPropertyChanging("Age");
                _Age = StructuralObject.SetValidValue(value, "Age");
                ReportPropertyChanged("Age");
                OnAgeChanged();
            }
        }
        private global::System.Int16 _Age;
        partial void OnAgeChanging(global::System.Int16 value);
        partial void OnAgeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CustEmail
        {
            get
            {
                return _CustEmail;
            }
            set
            {
                OnCustEmailChanging(value);
                ReportPropertyChanging("CustEmail");
                _CustEmail = StructuralObject.SetValidValue(value, false, "CustEmail");
                ReportPropertyChanged("CustEmail");
                OnCustEmailChanged();
            }
        }
        private global::System.String _CustEmail;
        partial void OnCustEmailChanging(global::System.String value);
        partial void OnCustEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CustPhone
        {
            get
            {
                return _CustPhone;
            }
            set
            {
                OnCustPhoneChanging(value);
                ReportPropertyChanging("CustPhone");
                _CustPhone = StructuralObject.SetValidValue(value, false, "CustPhone");
                ReportPropertyChanged("CustPhone");
                OnCustPhoneChanged();
            }
        }
        private global::System.String _CustPhone;
        partial void OnCustPhoneChanging(global::System.String value);
        partial void OnCustPhoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Gender
        {
            get
            {
                return _Gender;
            }
            set
            {
                OnGenderChanging(value);
                ReportPropertyChanging("Gender");
                _Gender = StructuralObject.SetValidValue(value, true, "Gender");
                ReportPropertyChanged("Gender");
                OnGenderChanged();
            }
        }
        private global::System.String _Gender;
        partial void OnGenderChanging(global::System.String value);
        partial void OnGenderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LoanCode
        {
            get
            {
                return _LoanCode;
            }
            set
            {
                OnLoanCodeChanging(value);
                ReportPropertyChanging("LoanCode");
                _LoanCode = StructuralObject.SetValidValue(value, false, "LoanCode");
                ReportPropertyChanged("LoanCode");
                OnLoanCodeChanged();
            }
        }
        private global::System.String _LoanCode;
        partial void OnLoanCodeChanging(global::System.String value);
        partial void OnLoanCodeChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LoanAppDataBaseModel", "FK_CustomerInfo_LoanDetails", "LoanDetails")]
        public LoanDetails LoanDetails
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<LoanDetails>("LoanAppDataBaseModel.FK_CustomerInfo_LoanDetails", "LoanDetails").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<LoanDetails>("LoanAppDataBaseModel.FK_CustomerInfo_LoanDetails", "LoanDetails").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<LoanDetails> LoanDetailsReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<LoanDetails>("LoanAppDataBaseModel.FK_CustomerInfo_LoanDetails", "LoanDetails");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<LoanDetails>("LoanAppDataBaseModel.FK_CustomerInfo_LoanDetails", "LoanDetails", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LoanAppDataBaseModel", Name="DocumentDetails")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DocumentDetails : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new DocumentDetails object.
        /// </summary>
        /// <param name="docCode">Initial value of the DocCode property.</param>
        /// <param name="docName">Initial value of the DocName property.</param>
        public static DocumentDetails CreateDocumentDetails(global::System.String docCode, global::System.String docName)
        {
            DocumentDetails documentDetails = new DocumentDetails();
            documentDetails.DocCode = docCode;
            documentDetails.DocName = docName;
            return documentDetails;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DocCode
        {
            get
            {
                return _DocCode;
            }
            set
            {
                if (_DocCode != value)
                {
                    OnDocCodeChanging(value);
                    ReportPropertyChanging("DocCode");
                    _DocCode = StructuralObject.SetValidValue(value, false, "DocCode");
                    ReportPropertyChanged("DocCode");
                    OnDocCodeChanged();
                }
            }
        }
        private global::System.String _DocCode;
        partial void OnDocCodeChanging(global::System.String value);
        partial void OnDocCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DocName
        {
            get
            {
                return _DocName;
            }
            set
            {
                OnDocNameChanging(value);
                ReportPropertyChanging("DocName");
                _DocName = StructuralObject.SetValidValue(value, false, "DocName");
                ReportPropertyChanged("DocName");
                OnDocNameChanged();
            }
        }
        private global::System.String _DocName;
        partial void OnDocNameChanging(global::System.String value);
        partial void OnDocNameChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LoanAppDataBaseModel", "FK_LoanDetails_DocumentDetails", "LoanDetails")]
        public EntityCollection<LoanDetails> LoanDetails
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<LoanDetails>("LoanAppDataBaseModel.FK_LoanDetails_DocumentDetails", "LoanDetails");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<LoanDetails>("LoanAppDataBaseModel.FK_LoanDetails_DocumentDetails", "LoanDetails", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LoanAppDataBaseModel", Name="LoanDetails")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class LoanDetails : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new LoanDetails object.
        /// </summary>
        /// <param name="loanCode">Initial value of the LoanCode property.</param>
        /// <param name="loanType">Initial value of the LoanType property.</param>
        /// <param name="loanReq">Initial value of the LoanReq property.</param>
        /// <param name="loanSanc">Initial value of the LoanSanc property.</param>
        /// <param name="loanStatus">Initial value of the LoanStatus property.</param>
        /// <param name="rateOfInterest">Initial value of the RateOfInterest property.</param>
        /// <param name="loanTenure">Initial value of the loanTenure property.</param>
        /// <param name="loanEMI">Initial value of the LoanEMI property.</param>
        /// <param name="docCode">Initial value of the DocCode property.</param>
        public static LoanDetails CreateLoanDetails(global::System.String loanCode, global::System.String loanType, global::System.Int32 loanReq, global::System.Int32 loanSanc, global::System.Boolean loanStatus, global::System.Double rateOfInterest, global::System.Int32 loanTenure, global::System.Int32 loanEMI, global::System.String docCode)
        {
            LoanDetails loanDetails = new LoanDetails();
            loanDetails.LoanCode = loanCode;
            loanDetails.LoanType = loanType;
            loanDetails.LoanReq = loanReq;
            loanDetails.LoanSanc = loanSanc;
            loanDetails.LoanStatus = loanStatus;
            loanDetails.RateOfInterest = rateOfInterest;
            loanDetails.loanTenure = loanTenure;
            loanDetails.LoanEMI = loanEMI;
            loanDetails.DocCode = docCode;
            return loanDetails;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LoanCode
        {
            get
            {
                return _LoanCode;
            }
            set
            {
                if (_LoanCode != value)
                {
                    OnLoanCodeChanging(value);
                    ReportPropertyChanging("LoanCode");
                    _LoanCode = StructuralObject.SetValidValue(value, false, "LoanCode");
                    ReportPropertyChanged("LoanCode");
                    OnLoanCodeChanged();
                }
            }
        }
        private global::System.String _LoanCode;
        partial void OnLoanCodeChanging(global::System.String value);
        partial void OnLoanCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LoanType
        {
            get
            {
                return _LoanType;
            }
            set
            {
                OnLoanTypeChanging(value);
                ReportPropertyChanging("LoanType");
                _LoanType = StructuralObject.SetValidValue(value, false, "LoanType");
                ReportPropertyChanged("LoanType");
                OnLoanTypeChanged();
            }
        }
        private global::System.String _LoanType;
        partial void OnLoanTypeChanging(global::System.String value);
        partial void OnLoanTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 LoanReq
        {
            get
            {
                return _LoanReq;
            }
            set
            {
                OnLoanReqChanging(value);
                ReportPropertyChanging("LoanReq");
                _LoanReq = StructuralObject.SetValidValue(value, "LoanReq");
                ReportPropertyChanged("LoanReq");
                OnLoanReqChanged();
            }
        }
        private global::System.Int32 _LoanReq;
        partial void OnLoanReqChanging(global::System.Int32 value);
        partial void OnLoanReqChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 LoanSanc
        {
            get
            {
                return _LoanSanc;
            }
            set
            {
                OnLoanSancChanging(value);
                ReportPropertyChanging("LoanSanc");
                _LoanSanc = StructuralObject.SetValidValue(value, "LoanSanc");
                ReportPropertyChanged("LoanSanc");
                OnLoanSancChanged();
            }
        }
        private global::System.Int32 _LoanSanc;
        partial void OnLoanSancChanging(global::System.Int32 value);
        partial void OnLoanSancChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean LoanStatus
        {
            get
            {
                return _LoanStatus;
            }
            set
            {
                OnLoanStatusChanging(value);
                ReportPropertyChanging("LoanStatus");
                _LoanStatus = StructuralObject.SetValidValue(value, "LoanStatus");
                ReportPropertyChanged("LoanStatus");
                OnLoanStatusChanged();
            }
        }
        private global::System.Boolean _LoanStatus;
        partial void OnLoanStatusChanging(global::System.Boolean value);
        partial void OnLoanStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double RateOfInterest
        {
            get
            {
                return _RateOfInterest;
            }
            set
            {
                OnRateOfInterestChanging(value);
                ReportPropertyChanging("RateOfInterest");
                _RateOfInterest = StructuralObject.SetValidValue(value, "RateOfInterest");
                ReportPropertyChanged("RateOfInterest");
                OnRateOfInterestChanged();
            }
        }
        private global::System.Double _RateOfInterest;
        partial void OnRateOfInterestChanging(global::System.Double value);
        partial void OnRateOfInterestChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 loanTenure
        {
            get
            {
                return _loanTenure;
            }
            set
            {
                OnloanTenureChanging(value);
                ReportPropertyChanging("loanTenure");
                _loanTenure = StructuralObject.SetValidValue(value, "loanTenure");
                ReportPropertyChanged("loanTenure");
                OnloanTenureChanged();
            }
        }
        private global::System.Int32 _loanTenure;
        partial void OnloanTenureChanging(global::System.Int32 value);
        partial void OnloanTenureChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 LoanEMI
        {
            get
            {
                return _LoanEMI;
            }
            set
            {
                OnLoanEMIChanging(value);
                ReportPropertyChanging("LoanEMI");
                _LoanEMI = StructuralObject.SetValidValue(value, "LoanEMI");
                ReportPropertyChanged("LoanEMI");
                OnLoanEMIChanged();
            }
        }
        private global::System.Int32 _LoanEMI;
        partial void OnLoanEMIChanging(global::System.Int32 value);
        partial void OnLoanEMIChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DocCode
        {
            get
            {
                return _DocCode;
            }
            set
            {
                OnDocCodeChanging(value);
                ReportPropertyChanging("DocCode");
                _DocCode = StructuralObject.SetValidValue(value, false, "DocCode");
                ReportPropertyChanged("DocCode");
                OnDocCodeChanged();
            }
        }
        private global::System.String _DocCode;
        partial void OnDocCodeChanging(global::System.String value);
        partial void OnDocCodeChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LoanAppDataBaseModel", "FK_CustomerInfo_LoanDetails", "CustomerInfo")]
        public EntityCollection<CustomerInfo> CustomerInfo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CustomerInfo>("LoanAppDataBaseModel.FK_CustomerInfo_LoanDetails", "CustomerInfo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CustomerInfo>("LoanAppDataBaseModel.FK_CustomerInfo_LoanDetails", "CustomerInfo", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LoanAppDataBaseModel", "FK_LoanDetails_DocumentDetails", "DocumentDetails")]
        public DocumentDetails DocumentDetails
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DocumentDetails>("LoanAppDataBaseModel.FK_LoanDetails_DocumentDetails", "DocumentDetails").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DocumentDetails>("LoanAppDataBaseModel.FK_LoanDetails_DocumentDetails", "DocumentDetails").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<DocumentDetails> DocumentDetailsReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DocumentDetails>("LoanAppDataBaseModel.FK_LoanDetails_DocumentDetails", "DocumentDetails");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<DocumentDetails>("LoanAppDataBaseModel.FK_LoanDetails_DocumentDetails", "DocumentDetails", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
